services:
  web_frontend:
    # 告訴 docker-compose 使用當前目錄下的 Dockerfile 構建映像檔
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-static-demo:latest # 映像檔名稱
    container_name: demo_frontend_web
    restart: always
    ports:
      # 將主機的 8080 端口映射到容器的 80 端口
      - "8080:80"
    # volumes:
      # 可選：如果需要即時更新靜態檔案，可取消註釋此行
      # - ../frontend/dist:/usr/share/nginx/html:ro